#!/usr/bin/env bash
# run_sweep.sh
# Trains and tests the Q-learning agent across a grid of episode counts and
# epsilon decay rates, then generates per-run plots and a single summary file.
#
# Usage (run from anywhere):
#   bash run_sweep.sh
#
# Output layout:
#   results/
#     summary.txt                         <- all numeric results, every run
#     ep<N>_decay<D>/
#       graphs/
#         reward_timeline.png
#         reward_smoothed.png
#         step_distribution.png
#         qtable_growth.png               <- training only
#         outcome_distribution.png
#         move_heatmap.png
#         target_heatmap.png
#         decision_split.png
#       Q_table_<N>_<D>.pickle
#       stats_<N>_<D>.pickle

set -euo pipefail

# ── parameter grid ────────────────────────────────────────────────────────────

EPISODE_COUNTS=(10000 50000 100000)
DECAY_RATES=(0.9995 0.9999)

# ── config ────────────────────────────────────────────────────────────────────

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QLEARN="${PROJECT_ROOT}/environment_static/Q_learn.py"
PLOT="${PROJECT_ROOT}/analysis/plot_run.py"
SUMMARIZE="${PROJECT_ROOT}/analysis/summarize_run.py"
RESULTS_DIR="${PROJECT_ROOT}/results"
SUMMARY_FILE="${RESULTS_DIR}/summary.txt"
PYTHON="${PYTHON:-/Users/gtheming/miniconda3/envs/cs4100/bin/python3}"

# ── setup ─────────────────────────────────────────────────────────────────────

mkdir -p "${RESULTS_DIR}"

cat > "${SUMMARY_FILE}" << 'EOF'
RRPS Q-LEARNING SWEEP RESULTS
Generated by run_sweep.sh
================================================================================

Columns
  phase         : train | test
  episodes      : number of training episodes
  decay         : epsilon decay rate per episode
  avg_reward    : mean total reward per episode
  win_pct       : % episodes agent finished with stars > 3
  loss_pct      : % episodes agent finished with stars <= 3
  trunc_pct     : % episodes that hit the step limit
  rand_pct      : % decisions made randomly (epsilon-greedy exploration)
  table_pct     : % decisions made from Q-table
  table_states  : Q-table size at end of training (train phase only)
  total_time_s  : wall-clock seconds for the phase
  avg_ep_ms     : average milliseconds per episode

--------------------------------------------------------------------------------
EOF

printf "%-8s %-10s %-8s %-12s %-8s %-8s %-8s %-8s %-8s %-14s %-12s %-12s\n" \
    "phase" "episodes" "decay" "avg_reward" "win%" "loss%" "trunc%" \
    "rand%" "table%" "table_states" "total_s" "avg_ms" \
    >> "${SUMMARY_FILE}"

printf '%s\n' "$(printf '─%.0s' {1..116})" >> "${SUMMARY_FILE}"

# ── sweep ─────────────────────────────────────────────────────────────────────

total_runs=$(( ${#EPISODE_COUNTS[@]} * ${#DECAY_RATES[@]} ))
run_index=0

for N_EP in "${EPISODE_COUNTS[@]}"; do
    for DECAY in "${DECAY_RATES[@]}"; do
        run_index=$(( run_index + 1 ))
        RUN_TAG="ep${N_EP}_decay${DECAY}"
        RUN_DIR="${RESULTS_DIR}/${RUN_TAG}"
        GRAPH_DIR="${RUN_DIR}/graphs"

        echo ""
        echo "════════════════════════════════════════════════════════"
        echo "  Run ${run_index}/${total_runs}: episodes=${N_EP}  decay=${DECAY}"
        echo "════════════════════════════════════════════════════════"

        mkdir -p "${GRAPH_DIR}"

        # ── train ────────────────────────────────────────────────
        echo "  [1/2] Training..."
        PYTHONPATH="${PROJECT_ROOT}" "${PYTHON}" -u "${QLEARN}" train \
            --episodes "${N_EP}" \
            --decay    "${DECAY}" \
            --outdir   "${RUN_DIR}"

        # ── test ─────────────────────────────────────────────────
        echo "  [2/2] Testing..."
        PYTHONPATH="${PROJECT_ROOT}" "${PYTHON}" -u "${QLEARN}" test \
            --episodes "${N_EP}" \
            --decay    "${DECAY}" \
            --outdir   "${RUN_DIR}"

        # ── plot ─────────────────────────────────────────────────
        echo "  Generating graphs → ${GRAPH_DIR}"
        PYTHONPATH="${PROJECT_ROOT}" "${PYTHON}" "${PLOT}" \
            --stats  "${RUN_DIR}/stats_${N_EP}_${DECAY}.pickle" \
            --outdir "${GRAPH_DIR}" \
            --tag    "${RUN_TAG}"

        # ── append numeric summary ────────────────────────────────
        PYTHONPATH="${PROJECT_ROOT}" "${PYTHON}" "${SUMMARIZE}" \
            --stats    "${RUN_DIR}/stats_${N_EP}_${DECAY}.pickle" \
            --episodes "${N_EP}" \
            --decay    "${DECAY}" \
            >> "${SUMMARY_FILE}"

        echo "  Done. Artifacts in ${RUN_DIR}"
    done
done

echo ""
echo "════════════════════════════════════════════════════════"
echo "  Sweep complete."
echo "  Summary → ${SUMMARY_FILE}"
echo "════════════════════════════════════════════════════════"